# .gitpod.yml

tasks:
  - name: Install Dependencies
    command: |
      if [ -d frontend ]; then cd frontend && npm install && cd ..; fi
      if [ -d api ]; then cd api && npm install && cd ..; fi
  - name: Start Development Servers
    command: |
      if [ -d frontend ]; then cd frontend && npm run dev & fi
      if [ -d api ]; then cd api && npm run dev & fi

ports:
  - port: 3000
    onOpen: open-preview
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
