# .gitpod.yml
tasks:
  - name: Install Dependencies
    command: |
      cd frontend && npm install && cd ../api && npm install
  - name: Start Development Servers
    init: |
      cd frontend && npm install
      cd ../api && npm install
    command: |
      cd frontend && npm run dev &
      cd ../api && npm run dev &
ports:
  - port: 3000
    onOpen: open-preview
  - port: 4000
    onOpen: open-preview
env:
  # Example Environment Variables
  NUXT_PUBLIC_API_URL: "http://localhost:4000"
  API_SECRET_KEY: "your-secret-key-here"
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
